"""WebVTT writer round-trip — manual parser, no external deps."""

from __future__ import annotations

import pytest

from maktaba_pipeline.media.subtitles.cue import Cue
from maktaba_pipeline.media.subtitles.vtt_writer import (
    format_vtt_timestamp,
    write_vtt,
)


@pytest.mark.unit
def test_vtt_timestamp_uses_period_decimal() -> None:
    assert format_vtt_timestamp(1.5) == "00:00:01.500"


@pytest.mark.unit
def test_vtt_timestamp_clamps_negative() -> None:
    assert format_vtt_timestamp(-3.0) == "00:00:00.000"


@pytest.mark.unit
def test_write_vtt_emits_magic_header() -> None:
    out = write_vtt([Cue(start_sec=0.0, end_sec=1.0, lines=("hi",))]).decode("utf-8")
    assert out.startswith("WEBVTT\n")


@pytest.mark.unit
def test_write_vtt_writes_period_decimal_timestamps() -> None:
    cue = Cue(start_sec=1.0, end_sec=2.5, lines=("hello",))
    out = write_vtt([cue]).decode("utf-8")
    assert "00:00:01.000 --> 00:00:02.500" in out


@pytest.mark.unit
def test_write_vtt_emits_cue_id_when_set() -> None:
    cue = Cue(
        start_sec=0.0,
        end_sec=1.0,
        lines=("x",),
        cue_id="seq-7",
    )
    out = write_vtt([cue]).decode("utf-8")
    # The cue id is the first line of the block; the timestamp follows.
    assert "seq-7\n00:00:00.000 --> 00:00:01.000" in out


@pytest.mark.unit
def test_write_vtt_speaker_wraps_in_voice_tag() -> None:
    cue = Cue(
        start_sec=0.0,
        end_sec=1.0,
        lines=("line one", "line two"),
        speaker="Alice",
    )
    out = write_vtt([cue]).decode("utf-8")
    assert "<v Alice>line one\nline two</v>" in out


@pytest.mark.unit
def test_write_vtt_escapes_html_in_body() -> None:
    cue = Cue(start_sec=0.0, end_sec=1.0, lines=("Tom & <Jerry>",))
    out = write_vtt([cue]).decode("utf-8")
    assert "Tom &amp; &lt;Jerry&gt;" in out


@pytest.mark.unit
def test_write_vtt_escapes_speaker_label() -> None:
    cue = Cue(
        start_sec=0.0,
        end_sec=1.0,
        lines=("hi",),
        speaker="Q & A",
    )
    out = write_vtt([cue]).decode("utf-8")
    assert "<v Q &amp; A>" in out


@pytest.mark.unit
def test_write_vtt_header_notes() -> None:
    out = write_vtt(
        [Cue(start_sec=0.0, end_sec=1.0, lines=("hi",))],
        header_notes=("generated by Maktaba",),
    ).decode("utf-8")
    assert "NOTE generated by Maktaba" in out


@pytest.mark.unit
def test_write_vtt_returns_bytes() -> None:
    out = write_vtt([Cue(start_sec=0.0, end_sec=1.0, lines=("x",))])
    assert isinstance(out, bytes)


@pytest.mark.unit
def test_write_vtt_separates_cues_with_blank_line() -> None:
    cues = [
        Cue(start_sec=0.0, end_sec=1.0, lines=("a",)),
        Cue(start_sec=1.0, end_sec=2.0, lines=("b",)),
    ]
    out = write_vtt(cues).decode("utf-8")
    assert "a\n\n00:00:01.000 --> 00:00:02.000\nb" in out
