// swift-tools-version:5.9
import PackageDescription

// This SwiftPM manifest exists so the app's sources compile and (where
// applicable) unit-test on a CI runner that has no tvOS SDK. The
// shippable artifact is an Xcode app target generated by the
// `tv-build-ios` Make target — Package.swift is the structural source
// of truth, not the build product.
//
// tvOS 17 is the floor (focus-engine APIs, `.searchable` dictation,
// `ContentUnavailableView`). macOS 14 is declared only so the same code
// type-checks host-side; SwiftUI / AVKit are available there too.
let package = Package(
    name: "MaktabaTV",
    platforms: [.tvOS(.v17), .macOS(.v14)],
    targets: [
        .executableTarget(
            name: "MaktabaTV",
            path: "MaktabaTV",
            exclude: [
                "Info.plist",
                "Resources/Assets.xcassets",
            ]
        )
    ]
)
